db:
  host: "172.31.26.109"
  username: "application"
  db: "appdb"
  password: "applicationP@33word"
  tablename: "incident_summary"
  updatetablename: "incident_summary_time"
  port: 3306
mongodb:
  host: "172.31.26.109"
  port: 27017
  username: ""
  password: ""
  connect: False
  database: "history"
  collection: "reports"
apis:
  getsummarytime: "http://10.0.153.141:8000/summarytime"
  updatesummarytime: "http://10.0.153.141:8000/updatesummarytime"

